# Generated by Django 5.1.1 on 2024-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Token"),
        ),
    ]