# Generated by Django 5.1.1 on 2024-10-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Введите имя", max_length=100, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(help_text="Введите номер телефона", max_length=20, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(help_text="Введите Email", max_length=254, verbose_name="Email")),
                ("address", models.TextField(help_text="Введите адресс", verbose_name="Адресс")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["name"],
            },
        ),
    ]